// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ksl.yardsales.domain;

import com.ksl.yardsales.domain.Address;
import com.ksl.yardsales.domain.AddressDataOnDemand;
import com.ksl.yardsales.repository.AddressRepository;
import com.ksl.yardsales.service.AddressService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AddressDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AddressDataOnDemand: @Component;
    
    private Random AddressDataOnDemand.rnd = new SecureRandom();
    
    private List<Address> AddressDataOnDemand.data;
    
    @Autowired
    AddressService AddressDataOnDemand.addressService;
    
    @Autowired
    AddressRepository AddressDataOnDemand.addressRepository;
    
    public Address AddressDataOnDemand.getNewTransientAddress(int index) {
        Address obj = new Address();
        setAddress(obj, index);
        setCity(obj, index);
        setLatitude(obj, index);
        setLongitude(obj, index);
        setState(obj, index);
        setZipcode(obj, index);
        return obj;
    }
    
    public void AddressDataOnDemand.setAddress(Address obj, int index) {
        String address = "address_" + index;
        obj.setAddress(address);
    }
    
    public void AddressDataOnDemand.setCity(Address obj, int index) {
        String city = "city_" + index;
        obj.setCity(city);
    }
    
    public void AddressDataOnDemand.setLatitude(Address obj, int index) {
        Float latitude = new Integer(index).floatValue();
        obj.setLatitude(latitude);
    }
    
    public void AddressDataOnDemand.setLongitude(Address obj, int index) {
        Float longitude = new Integer(index).floatValue();
        obj.setLongitude(longitude);
    }
    
    public void AddressDataOnDemand.setState(Address obj, int index) {
        String state = "state_" + index;
        obj.setState(state);
    }
    
    public void AddressDataOnDemand.setZipcode(Address obj, int index) {
        String zipcode = "zipcode_" + index;
        obj.setZipcode(zipcode);
    }
    
    public Address AddressDataOnDemand.getSpecificAddress(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Address obj = data.get(index);
        Long id = obj.getId();
        return addressService.findAddress(id);
    }
    
    public Address AddressDataOnDemand.getRandomAddress() {
        init();
        Address obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return addressService.findAddress(id);
    }
    
    public boolean AddressDataOnDemand.modifyAddress(Address obj) {
        return false;
    }
    
    public void AddressDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = addressService.findAddressEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Address' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Address>();
        for (int i = 0; i < 10; i++) {
            Address obj = getNewTransientAddress(i);
            try {
                addressService.saveAddress(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            addressRepository.flush();
            data.add(obj);
        }
    }
    
}
