// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ksl.yardsales.domain;

import com.ksl.yardsales.domain.YardSaleDataOnDemand;
import com.ksl.yardsales.domain.YardSaleIntegrationTest;
import com.ksl.yardsales.repository.YardSaleRepository;
import com.ksl.yardsales.service.YardSaleService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect YardSaleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: YardSaleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: YardSaleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: YardSaleIntegrationTest: @Transactional;
    
    @Autowired
    YardSaleDataOnDemand YardSaleIntegrationTest.dod;
    
    @Autowired
    YardSaleService YardSaleIntegrationTest.yardSaleService;
    
    @Autowired
    YardSaleRepository YardSaleIntegrationTest.yardSaleRepository;
    
    @Test
    public void YardSaleIntegrationTest.testCountAllYardSales() {
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", dod.getRandomYardSale());
        long count = yardSaleService.countAllYardSales();
        Assert.assertTrue("Counter for 'YardSale' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void YardSaleIntegrationTest.testFindYardSale() {
        YardSale obj = dod.getRandomYardSale();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to provide an identifier", id);
        obj = yardSaleService.findYardSale(id);
        Assert.assertNotNull("Find method for 'YardSale' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'YardSale' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void YardSaleIntegrationTest.testFindAllYardSales() {
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", dod.getRandomYardSale());
        long count = yardSaleService.countAllYardSales();
        Assert.assertTrue("Too expensive to perform a find all test for 'YardSale', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<YardSale> result = yardSaleService.findAllYardSales();
        Assert.assertNotNull("Find all method for 'YardSale' illegally returned null", result);
        Assert.assertTrue("Find all method for 'YardSale' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void YardSaleIntegrationTest.testFindYardSaleEntries() {
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", dod.getRandomYardSale());
        long count = yardSaleService.countAllYardSales();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<YardSale> result = yardSaleService.findYardSaleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'YardSale' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'YardSale' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void YardSaleIntegrationTest.testFlush() {
        YardSale obj = dod.getRandomYardSale();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to provide an identifier", id);
        obj = yardSaleService.findYardSale(id);
        Assert.assertNotNull("Find method for 'YardSale' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyYardSale(obj);
        Integer currentVersion = obj.getVersion();
        yardSaleRepository.flush();
        Assert.assertTrue("Version for 'YardSale' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void YardSaleIntegrationTest.testUpdateYardSaleUpdate() {
        YardSale obj = dod.getRandomYardSale();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to provide an identifier", id);
        obj = yardSaleService.findYardSale(id);
        boolean modified =  dod.modifyYardSale(obj);
        Integer currentVersion = obj.getVersion();
        YardSale merged = yardSaleService.updateYardSale(obj);
        yardSaleRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'YardSale' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void YardSaleIntegrationTest.testSaveYardSale() {
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", dod.getRandomYardSale());
        YardSale obj = dod.getNewTransientYardSale(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'YardSale' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'YardSale' identifier to be null", obj.getId());
        yardSaleService.saveYardSale(obj);
        yardSaleRepository.flush();
        Assert.assertNotNull("Expected 'YardSale' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void YardSaleIntegrationTest.testDeleteYardSale() {
        YardSale obj = dod.getRandomYardSale();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'YardSale' failed to provide an identifier", id);
        obj = yardSaleService.findYardSale(id);
        yardSaleService.deleteYardSale(obj);
        yardSaleRepository.flush();
        Assert.assertNull("Failed to remove 'YardSale' with identifier '" + id + "'", yardSaleService.findYardSale(id));
    }
    
}
