// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ksl.yardsales.domain;

import com.ksl.yardsales.domain.YardSaleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect YardSaleDataOnDemand_Roo_Configurable {
    
    declare @type: YardSaleDataOnDemand: @Configurable;
    
}
