// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ksl.yardsales.domain;

import com.ksl.yardsales.domain.YardSale;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect YardSale_Roo_Configurable {
    
    declare @type: YardSale: @Configurable;
    
}
